volumes:
  postgres_data:

networks:
  trust:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - trust
    environment:
      - SKIP_PREFLIGHT_CHECK="true"
      - VITE_API_URL=http://localhost:3080/api/v1
  trust-api:
    build:
      context: ./server
    ports:
      - "3080:3080"
    environment:
      - DB_HOST=db
      - DB_USER=kadi
      - DB_PASSWORD=kadi010203
      - DB_NAME=ecomdb
      - JWTSecret=hellotherebuddyhru
    volumes:
      - ./server:/usr/src/app
      - ./server/public:/usr/src/app/public
    networks:
      - trust
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=kadi
      - POSTGRES_PASSWORD=kadi010203
      - POSTGRES_DB=ecomdb
    ports:
      - "5432:5432"
    networks:
      - trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kadi -d ecomdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    networks:
      - trust
    depends_on:
      - db
