export const abi = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [],
  },
  {
    type: "event",
    name: "OfferCreated",
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "offerAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tender",
        type: "address",
      },
    ],
  },
  {
    type: "function",
    name: "TENDER_ROLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "ENTREPRENEUR_ROLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "EXPERT_ROLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "allOffers",
    stateMutability: "view",
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    outputs: [{ internalType: "address", name: "", type: "address" }],
  },
  {
    type: "function",
    name: "grantTender",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revokeTender",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "grantEntrepreneur",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revokeEntrepreneur",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "grantExpert",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revokeExpert",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "hasRole",
    stateMutability: "view",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "createOffer",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "grantRole",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "revokeRole",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getRoleAdmin",
    stateMutability: "view",
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "renounceRole",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "supportsInterface",
    stateMutability: "view",
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
  },
];
